# Generated by Django 6.0.1 on 2026-01-11 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('stripe_customer_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(help_text="Subdomain for this instance (e.g., 'janes-shop' for janes-shop.ebuilder.host)", max_length=63, unique=True)),
                ('custom_domain', models.CharField(blank=True, help_text="Optional custom domain (e.g., 'shop.janesdomain.com')", max_length=255)),
                ('container_id', models.CharField(blank=True, max_length=64)),
                ('container_name', models.CharField(blank=True, max_length=255)),
                ('port', models.IntegerField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Error details or status info')),
                ('site_name', models.CharField(default='My Shop', max_length=255)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_password', models.CharField(blank=True, help_text='Temporary password (should be changed by user)', max_length=255)),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.customer')),
            ],
            options={
                'verbose_name': 'Instance',
                'verbose_name_plural': 'Instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvisioningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create Instance'), ('start', 'Start Instance'), ('stop', 'Stop Instance'), ('restart', 'Restart Instance'), ('delete', 'Delete Instance'), ('health_check', 'Health Check'), ('webhook', 'Stripe Webhook'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.instance')),
            ],
            options={
                'verbose_name': 'Provisioning Log',
                'verbose_name_plural': 'Provisioning Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=255, unique=True)),
                ('stripe_price_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('unpaid', 'Unpaid'), ('trialing', 'Trialing')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
