# Generated by Django 6.0.1 on 2026-01-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
