# Generated by Django 6.0.1 on 2026-01-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instance_welcome_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='portal_password',
            field=models.CharField(blank=True, help_text='Hashed password for customer portal login', max_length=128),
        ),
    ]
