# Generated by Django 6.0.1 on 2026-01-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_portal_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='custom_domain_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instance',
            name='custom_domain_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instance',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
