"""
Nginx Configuration Manager

Generates and manages nginx reverse proxy configs for customer instances.
Each customer gets a subdomain like customer.djangify.com
"""

import os
import subprocess
from django.conf import settings
from .models import Instance, ProvisioningLog


class NginxManager:
    """
    Manages nginx configurations for eBuilder instances.

    Each instance gets a config like:
    /etc/nginx/conf.d/domains/ebuilder-janes-shop.conf
    """

    def __init__(self):
        self.config_dir = settings.NGINX_CONFIG_DIR
        self.base_domain = settings.BASE_DOMAIN
        self.server_ip = settings.SERVER_IP

    def log(self, instance, message):
        """Log nginx actions"""
        ProvisioningLog.objects.create(
            instance=instance,
            action="create",
            message=f"[NGINX] {message}",
        )

    def ensure_config_dir(self):
        """Ensure nginx config directory exists"""
        os.makedirs(self.config_dir, exist_ok=True)

    def get_config_path(self, instance):
        """Get the config file path for an instance"""
        return os.path.join(self.config_dir, f"ebuilder-{instance.subdomain}.conf")

    def generate_config(self, instance):
        """
        Generate nginx config for an instance.

        Handles:
        - Subdomain routing
        - Custom domain (only if verified)
        - SSL (wildcard OR custom domain cert)
        - WebSocket support
        - Proxy headers
        """

        # ---------------------------
        # Server names
        # ---------------------------
        server_names = [f"{instance.subdomain}.{self.base_domain}"]

        # Only add custom domain if it exists, is non-empty, AND is verified
        if (
            instance.custom_domain
            and instance.custom_domain.strip()
            and instance.custom_domain_verified
        ):
            server_names.append(instance.custom_domain)
            if not instance.custom_domain.startswith("www."):
                server_names.append(f"www.{instance.custom_domain}")

        # ---------------------------
        # SSL selection
        # ---------------------------
        if (
            instance.custom_domain
            and instance.custom_domain.strip()
            and instance.custom_domain_ssl
        ):
            ssl_cert = f"/etc/letsencrypt/live/{instance.custom_domain}/fullchain.pem"
            ssl_key = f"/etc/letsencrypt/live/{instance.custom_domain}/privkey.pem"
        else:
            ssl_cert = settings.WILDCARD_SSL_CERT
            ssl_key = settings.WILDCARD_SSL_KEY

        # ---------------------------
        # Config
        # ---------------------------
        config = f"""# Auto-generated by eBuilder Provisioner
# Instance: {instance.subdomain}
# Customer: {instance.customer.email}
# Generated: {instance.updated_at}

upstream ebuilder_{instance.subdomain} {{
    server 127.0.0.1:{instance.port};
}}

server {{
    listen {self.server_ip}:80;
    listen [::]:80;
    server_name {" ".join(server_names)};

    # Redirect to HTTPS
    return 301 https://$host$request_uri;
}}

server {{
    listen {self.server_ip}:443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name {" ".join(server_names)};

    # SSL Configuration
    ssl_certificate {ssl_cert};
    ssl_certificate_key {ssl_key};
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    # Modern SSL configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    # HSTS
    add_header Strict-Transport-Security "max-age=63072000" always;

    # Logging
    access_log /var/log/nginx/ebuilder-{instance.subdomain}-access.log;
    error_log /var/log/nginx/ebuilder-{instance.subdomain}-error.log;

    # Max upload size
    client_max_body_size 100M;

    # Proxy to container
    location / {{
        proxy_pass http://ebuilder_{instance.subdomain};
        proxy_http_version 1.1;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }}

    # Static files
    location /static/ {{
        alias /home/ebuilder/staticfiles/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }}

    # Media files
    location /media/ {{
        proxy_pass http://ebuilder_{instance.subdomain};
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}
}}
"""
        return config

    def write_config(self, instance):
        """Write the nginx config file for an instance"""
        self.ensure_config_dir()
        config_path = self.get_config_path(instance)
        config_content = self.generate_config(instance)

        try:
            with open(config_path, "w") as f:
                f.write(config_content)
            self.log(instance, f"Wrote nginx config to {config_path}")
            return True

        except Exception as e:
            self.log(instance, f"Failed to write nginx config: {e}")
            raise

    def remove_config(self, instance):
        """Remove the nginx config file for an instance"""
        config_path = self.get_config_path(instance)

        try:
            if os.path.exists(config_path):
                os.remove(config_path)
                self.log(instance, f"Removed nginx config {config_path}")
            return True
        except Exception as e:
            self.log(instance, f"Failed to remove nginx config: {e}")
            raise

    def test_config(self):
        """Test nginx configuration syntax"""
        try:
            result = subprocess.run(
                ["/usr/bin/sudo", "/usr/sbin/nginx", "-t"],
                capture_output=True,
                text=True,
            )
            output = result.stderr or result.stdout
            return result.returncode == 0, output
        except Exception as e:
            return False, str(e)

    def reload_nginx(self):
        """Reload nginx to apply new configuration"""
        try:
            result = subprocess.run(
                ["/usr/bin/sudo", "/usr/bin/systemctl", "reload", "nginx"],
                capture_output=True,
                text=True,
            )
            return result.returncode == 0
        except Exception as e:
            return False

    def provision_nginx(self, instance):
        """
        Full nginx provisioning:
        1. Write config
        2. Test config
        3. Reload nginx
        """
        # Write config
        self.write_config(instance)

        # Test config
        valid, error = self.test_config()
        if not valid:
            # Roll back
            self.remove_config(instance)
            raise Exception(f"Invalid nginx config: {error}")

        # Reload
        if not self.reload_nginx():
            raise Exception("Failed to reload nginx")

        self.log(instance, "Nginx provisioning complete")
        return True

    def deprovision_nginx(self, instance):
        """
        Remove nginx config and reload.
        """
        self.remove_config(instance)
        self.reload_nginx()
        self.log(instance, "Nginx deprovisioning complete")
        return True


def generate_all_configs():
    """
    Regenerate all nginx configs.
    Useful after updates or recovery.
    """
    manager = NginxManager()

    for instance in Instance.objects.filter(status="running"):
        try:
            manager.write_config(instance)
            print(f"Generated config for {instance.subdomain}")
        except Exception as e:
            print(f"Failed for {instance.subdomain}: {e}")

    # Test and reload
    valid, error = manager.test_config()
    if valid:
        manager.reload_nginx()
        print("Nginx reloaded successfully")
    else:
        print(f"Config test failed: {error}")
